----
- hosts: devops
  become: yes
  tasks:
   - name: changing native group driver 
     shell:
      mkdir /etc/docker
     ignore_errors: yes

   - name: changing native group driver 
     shell:
      cmd: |
       cat <<EOF > /etc/docker/daemon.json
       {
         "exec-opts": ["native.cgroupdriver=systemd"],
         "log-driver": "json-file",
        "log-opts": {
         "max-size": "100m"
        },
         "storage-driver": "overlay2",
         "storage-opts": [
         "overlay2.override_kernel_check=true"
        ]
        }
        
   - name: changing native group driver 
     shell:
      mkdir -p /etc/systemd/system/docker.service.d
      systemctl daemon-reload
      systemctl restart docker
   - name: Fixing cent_os traffic routing issues
     shell:
      cmd: |
       cat <<EOF > /etc/sysctl.d/k8s.conf
       net.bridge.bridge-nf-call-ip6tables = 1
       net.bridge.bridge-nf-call-iptables = 1

   - name: Fixing cent_os traffic routing issues
     shell:
      sysctl --system
   